-- PER-ARTICLE 'HOW I HELP' SECTIONS - run once in Supabase SQL Editor.
-- Each statement is guarded with NOT LIKE, so re-running is safe.
BEGIN;

UPDATE blog_posts SET body = replace(body, E'---\n\n**About this article.**', E'## Applying this to a real property\n\nWhen Pinilla makes your shortlist, I help you weigh its neighborhoods against each other and against current inventory, arrange private showings, and pin down the section-specific questions - fees, club access, rental rules - before you offer. From offer onward, I connect the independent attorney, escrow provider, inspector and surveyor the transaction needs and keep everyone moving.\n\n---\n\n**About this article.**')
WHERE slug = 'hacienda-pinilla-communities-amenities-guide' AND body NOT LIKE '%## Applying this to a real property%';

UPDATE blog_posts SET body = replace(body, E'---\n\n**About this article.**', E'## Applying this to a real property\n\nSeventeen sub-communities means seventeen fee schedules and rulebooks. I help you narrow them to the two or three that fit how you plan to use the property, tour them, and gather each section''s HOA documents. When you choose, I introduce the independent professionals who review title, inspection, escrow and closing - and I stay the point of contact between them.\n\n---\n\n**About this article.**')
WHERE slug = 'reserva-conchal-real-estate-communities-guide' AND body NOT LIKE '%## Applying this to a real property%';

UPDATE blog_posts SET body = replace(body, E'---\n\n**About this article.**', E'## What this means for your property search\n\nIf Senderos is on your list, I help you compare available homesites and any finished homes, walk the community so the views and lots are real rather than renderings, and request the current design guidelines and club terms in writing. Building here means coordination - architect, attorney, escrow, and later construction contacts - and I help keep that organized from lot choice to keys.\n\n---\n\n**About this article.**')
WHERE slug = 'senderos-tamarindo-real-estate-guide' AND body NOT LIKE '%## What this means for your property search%';

UPDATE blog_posts SET body = replace(body, E'---\n\n**About this article.**', E'## How I help buyers navigate this step\n\nIn a development still building out, my job is to keep the questions sharp: what is delivered versus planned, what the developer documents commit to with dates, and how a lot compares with a turnkey Hilltop home. I arrange the tour, help you request the HOA and construction documents named above, and bring in the independent attorney and specialists when an offer takes shape.\n\n---\n\n**About this article.**')
WHERE slug = 'tamarindo-park-real-estate-buyers-guide' AND body NOT LIKE '%## How I help buyers navigate this step%';

UPDATE blog_posts SET body = replace(body, E'---\n\n**About this article.**', E'## How I help buyers navigate this step\n\nWith 73 properties, timing matters more than browsing - I help you see what is actually available across the nine subdivisions, tour it, and get the water and HOA questions answered in writing by the association. For lot purchases, I connect the independent surveyor, engineer and attorney who verify what the marketing cannot, and keep the process moving between them.\n\n---\n\n**About this article.**')
WHERE slug = 'las-ventanas-playa-grande-real-estate-guide' AND body NOT LIKE '%## How I help buyers navigate this step%';

UPDATE blog_posts SET body = replace(body, E'---\n\n**About this article.**', E'## What this means for your property search\n\nI help buyers compare Mar Vista''s finished homes, builds in progress and lots against each other - and against Reserva Conchal or Las Ventanas nearby - based on how you actually plan to live, school runs included. When a property gets serious, I request the association documents, organize inspections or survey verification with independent professionals, and coordinate through closing.\n\n---\n\n**About this article.**')
WHERE slug = 'mar-vista-flamingo-real-estate-guide' AND body NOT LIKE '%## What this means for your property search%';

UPDATE blog_posts SET body = replace(body, E'---\n\n**About this article.**', E'## How I help with this\n\nI help organize the real estate side of due diligence: keeping the buyer, seller, attorney, inspector and surveyor aligned, helping collect the documents on this list, arranging property access for inspections, and following up so the 15-to-30-day window is used well. The legal and technical judgments belong to the independent professionals - my job is that nothing sits waiting on a missing paper or an unanswered email.\n\n---\n\n**About this article.**')
WHERE slug = 'costa-rica-property-due-diligence-checklist' AND body NOT LIKE '%## How I help with this%';

UPDATE blog_posts SET body = replace(body, E'---\n\n**About this article.**', E'## Need help verifying the next step?\n\nBefore recommending land, I help buyers identify whether documented water availability exists for the specific lot - and when it doesn''t, I connect the attorney, engineer, or the right municipality or ASADA contact for independent verification. I don''t issue or interpret the letter; I make sure the question gets asked before your money is committed, not after.\n\n---\n\n**About this article.**')
WHERE slug = 'costa-rica-property-water-letter-guide' AND body NOT LIKE '%## Need help verifying the next step?%';

UPDATE blog_posts SET body = replace(body, E'---\n\n**About this article.**', E'## How I help with this\n\nI don''t provide legal title opinions or boundary certifications - that is attorney and surveyor work. What I do: help gather the property''s available information early, connect you with an independent Costa Rican attorney and licensed surveyor, and keep communication moving during due diligence so a title-versus-plano discrepancy surfaces with time to fix it, not at the closing table.\n\n---\n\n**About this article.**')
WHERE slug = 'costa-rica-property-title-plano-catastrado-guide' AND body NOT LIKE '%## How I help with this%';

UPDATE blog_posts SET body = replace(body, E'---\n\n**About this article.**', E'## Applying this to a real lot\n\nLand is where I slow buyers down, in a good way. I help you run this checklist against a specific lot - which questions are already answered, which need the municipality, and which need a professional - then connect the independent surveyor, engineer, water contact and attorney to evaluate what I can''t. If you''re comparing two or three lots, I''ll help you see which one''s unknowns are cheapest to resolve.\n\n---\n\n**About this article.**')
WHERE slug = 'buying-land-guanacaste-zoning-water-building-checklist' AND body NOT LIKE '%## Applying this to a real lot%';

UPDATE blog_posts SET body = body || E'\n\n## How I help buyers navigate this\n\nKnowing the process is different from running it from another country. I help buyers organize each stage - offer, escrow, due diligence, closing - introduce the independent attorney and escrow provider the purchase needs, and keep communication moving so you always know what happens next. Start with what you''re looking for and where you are in the process, and I''ll help you identify the next step.'
WHERE slug = 'buying-property-costa-rica-foreigners-guide' AND body NOT LIKE '%## How I help buyers navigate this%';

UPDATE blog_posts SET body = body || E'\n\n## How I help with this\n\nI help buyers and sellers understand which of these costs to raise with their attorney, escrow provider, accountant or lender - and I can introduce the appropriate independent professionals for transaction-specific figures. What I don''t do is quote your taxes for you: the numbers above are the framework, and the professionals put your name on them.'
WHERE slug = 'costa-rica-closing-costs-taxes' AND body NOT LIKE '%## How I help with this%';

UPDATE blog_posts SET body = body || E'\n\n## Need help verifying a specific property?\n\nWhether a property is titled or concession - and what its concession actually permits - is a determination for an independent Costa Rican attorney. I help by gathering the property''s available records early, flagging Maritime Zone questions before you fall in love with the view, and connecting the attorney who verifies the rest.'
WHERE slug = 'titled-vs-concession-beachfront-costa-rica' AND body NOT LIKE '%## Need help verifying a specific property?%';

UPDATE blog_posts SET body = body || E'\n\n## What this means for your property search\n\nReading about towns gets you to a shortlist; walking them decides it. I help buyers compare two or three towns against how they actually plan to live - then organize the property tours, current listings, and next steps in whichever one wins.'
WHERE slug = 'guanacaste-gold-coast-towns-guide' AND body NOT LIKE '%## What this means for your property search%';

UPDATE blog_posts SET body = body || E'\n\n## How I help investors evaluate this\n\nI help buyers compare specific properties on the things that can be documented - rental history, recurring costs, condition, location, management needs - and introduce independent property managers and accountants when the analysis needs professional depth. What I won''t do is promise returns: the honest version of this market is in the numbers of each property, not a headline.'
WHERE slug = 'guanacaste-real-estate-investment-2026' AND body NOT LIKE '%## How I help investors evaluate this%';

UPDATE blog_posts SET body = body || E'\n\n## How I help with this\n\nWhen a rental purchase gets serious, I help you request the property''s actual performance documentation, compare recurring costs and management options, and introduce independent property managers and accountants for the detailed analysis. Projections are easy to print - I help you check them against paper.'
WHERE slug = 'costa-rica-vacation-rental-income-guanacaste' AND body NOT LIKE '%## How I help with this%';

UPDATE blog_posts SET body = body || E'\n\n## Where I fit in\n\nReal estate and residency are separate processes. I handle the property side - search, offer, due diligence coordination, closing - and I can introduce an independent immigration attorney for residency-specific advice. If your plan ties the two together, tell me early: the $150,000 Inversionista path has ownership-structure implications your attorneys will want to align on.'
WHERE slug = 'costa-rica-residency-property-buyers' AND body NOT LIKE '%## Where I fit in%';

UPDATE blog_posts SET body = body || E'\n\n## Applying these numbers to your search\n\nAverages set expectations; specific homes set prices. I help buyers compare what is actually listed right now against these ranges, tour the candidates, and read whether an asking price reflects the market or hope. Sellers: if you want to know where your property genuinely sits in this table, I''ll give you an honest read - no obligation.'
WHERE slug = 'tamarindo-house-prices-2026' AND body NOT LIKE '%## Applying these numbers to your search%';

UPDATE blog_posts SET body = body || E'\n\n## How I help you decide\n\nIf you''re genuinely torn between the two, don''t decide from a browser. I help buyers structure a comparison trip, line up the right properties in each, and talk honestly about which trade-offs you''ll still care about in year three. Then we organize the process in whichever market fits.'
WHERE slug = 'tamarindo-vs-nosara-real-estate' AND body NOT LIKE '%## How I help you decide%';

UPDATE blog_posts SET body = body || E'\n\n## From school choice to home choice\n\nI help families compare communities against the daily logistics of a school run - real drive times, not map distances - and build a housing shortlist around them. Admissions, tuition and enrollment should always be confirmed directly with each school; when available, I can point you to the right admissions contact.'
WHERE slug = 'schools-guanacaste-gold-coast-guide' AND body NOT LIKE '%## From school choice to home choice%';

COMMIT;

-- Verify: should return 20 rows (each article contains its section)
SELECT slug FROM blog_posts b JOIN (VALUES ('hacienda-pinilla-communities-amenities-guide', '## Applying this to a real property'), ('reserva-conchal-real-estate-communities-guide', '## Applying this to a real property'), ('senderos-tamarindo-real-estate-guide', '## What this means for your property search'), ('tamarindo-park-real-estate-buyers-guide', '## How I help buyers navigate this step'), ('las-ventanas-playa-grande-real-estate-guide', '## How I help buyers navigate this step'), ('mar-vista-flamingo-real-estate-guide', '## What this means for your property search'), ('costa-rica-property-due-diligence-checklist', '## How I help with this'), ('costa-rica-property-water-letter-guide', '## Need help verifying the next step?'), ('costa-rica-property-title-plano-catastrado-guide', '## How I help with this'), ('buying-land-guanacaste-zoning-water-building-checklist', '## Applying this to a real lot'), ('buying-property-costa-rica-foreigners-guide', '## How I help buyers navigate this'), ('costa-rica-closing-costs-taxes', '## How I help with this'), ('titled-vs-concession-beachfront-costa-rica', '## Need help verifying a specific property?'), ('guanacaste-gold-coast-towns-guide', '## What this means for your property search'), ('guanacaste-real-estate-investment-2026', '## How I help investors evaluate this'), ('costa-rica-vacation-rental-income-guanacaste', '## How I help with this'), ('costa-rica-residency-property-buyers', '## Where I fit in'), ('tamarindo-house-prices-2026', '## Applying these numbers to your search'), ('tamarindo-vs-nosara-real-estate', '## How I help you decide'), ('schools-guanacaste-gold-coast-guide', '## From school choice to home choice')) v(s, h) ON b.slug = v.s AND b.body LIKE '%' || v.h || '%';
